version: '3'
services:
   mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'maria_db'
      MYSQL_USER: 'fuser'
      MYSQL_PASSWORD: 'fpass'
    ports:
        - "3307:3306"
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
