version: '3'
services:
 redis:
  image: sameersbn/redis:4.0.9-3
  ports:
    - "6379:6379"
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always
 mysql:
  image: mysql:8
  container_name: mysql_docker
  environment:
   MYSQL_DATABASE: 'fastapi_db'
   MYSQL_USER: 'fuser'
   MYSQL_PASSWORD: 'fpass'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - "3307:3306"
  volumes:
   - mysql_volume:/var/lib/mysql
volumes:
 mysql_volume: